#!/usr/bin/env python3
"""Write the Linux gfx1151 workflow for specs/amd_studio_vs_comfy.json into an amd_ci scaffold dir.

  python diffusion_bench/amd/gen_studio_vs_comfy_workflow.py --out ci_studio_vs_comfy

Five GPU jobs, chained with needs (+ if: always()) so only one of them ever waits on the shared GPU group:
  j1 Z-Image-Turbo + FLUX.2-klein-4B   j2 FLUX.1-schnell + SDXL   j3 Qwen-Image-2.1   j4 Wan2.2-TI2V-5B   j5 MiniMax-H3
Each job: states base = unsloth main at BASE_SHA, head = the same commit + amd_ci/patches/rocm_flash.patch (the local
Studio fix, applied on the runner; nothing of it is pushed to any unsloth repo); Studio via install.sh --local;
DAO-AILab flash-attention (Triton AMD backend, FA_SHA) into the Studio venv; ComfyUI at COMFY_SHA in two venvs (README
ROCm torch, and the gfx1151 torch Studio uses) + the same flash-attention; then differential.py over the job's cells.
No secret of any kind is referenced; HF_TOKEN never exists in the job.
"""

from __future__ import annotations

import argparse
import shlex
from pathlib import Path

BASE_SHA = "642da4cef9c1acd62c4c14ef74fd2e7317f4574a"
COMFY_SHA = "a7169322485d0049380fb207fa17e9fb3ec40486"
FA_SHA = "bbe25bacff9f337568b66e69950e549df9839068"
BRANCH = "amd-ci-studio-vs-comfy"

JOBS = [
    # id, title, base --only, head --state-only, criteria, defect
    ("j1_zimg_klein", "Z-Image-Turbo + FLUX.2-klein-4B",
     ["zimg_*", "klein_s_def", "klein_c_*"], ["zimg_s_*", "klein_s_*"], "differential", "slow:zimg_s_flash:zimg_s_def:0.9"),
    ("j2_flux1_sdxl", "FLUX.1-schnell + SDXL",
     ["flux1_*", "sdxl_s_def", "sdxl_c_*"], ["flux1_s_*", "sdxl_s_*"], "differential", "slow:flux1_s_flash:flux1_s_def:0.9"),
    ("j3_q21", "Qwen-Image-2.1", ["q21_*"], ["q21_s_*"], "differential", "slow:q21_s_flash:q21_s_def:0.9"),
    ("j4_wan", "Wan2.2-TI2V-5B short clip", ["wan_*"], ["wan_s_*"], "differential", "slow:wan_s_flash:wan_s_def:0.9"),
    ("j5_h3", "MiniMax-H3 (ComfyUI int8_convrot vs Studio GGUF)", ["h3_s_def", "h3_c_*"], ["h3_s_def"],
     "no_regression", None),
]

HEADER = f"""name: "AMD CI: Studio vs ComfyUI diffusion on gfx1151 (Linux)"

# Generated by diffusion_bench/amd/gen_studio_vs_comfy_workflow.py from the amd_ci scaffold (templates/workflow.yml):
# same preamble, gate, Studio install, differential and artifact plumbing, one GPU job per model group.
# Measurement only: no secret is referenced, every model is a public download (token=False).

on:
  push:
    branches: [{BRANCH}]
  workflow_dispatch:

permissions:
  contents: read

env:
  UPSTREAM: "https://github.com/unslothai/unsloth"
  BASE_SHA: "{BASE_SHA}"
  COMFY_SHA: "{COMFY_SHA}"
  FA_SHA: "{FA_SHA}"

jobs:
"""

JOB = """
  {jid}:
    name: "{title} (gfx1151, exclusive GPU)"
{needs}    runs-on: [self-hosted, Linux, strix-halo, devlab-dispatch]
    timeout-minutes: 600
    # The shared GPU group (see templates/workflow.yml): one GPU measurement at a time across all branches.
    concurrency:
      group: amd-ci-gfx1151-gpu
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with: {{ persist-credentials: false }}

      - name: Preamble
        run: |
          source amd_ci/lib/preamble.sh "svc-{jid}"

      - name: Hardware gate
        run: |
          set -euo pipefail
          python3 amd_ci/lib/gate.py --no-torch --require rocm gpu \\
            --expect-arch gfx1151 --min-gpus 1 \\
            --out "$AMD_CI_WORK/out/host.json" || \\
          echo "note: gate ran before the venv exists; re-gated after install below"

      - name: Disk, memory, cores
        run: |
          set +e
          df -h "$RUNNER_TEMP"
          free -g
          nproc
          exit 0

      - name: Resolve states (main, and main + the local ROCm flash patch)
        run: |
          set -euo pipefail
          git clone -q --filter=blob:none "$UPSTREAM" "$AMD_CI_WORK/repo"
          git -C "$AMD_CI_WORK/repo" worktree add -q --detach "$AMD_CI_WORK/states/base" "$BASE_SHA"
          git -C "$AMD_CI_WORK/repo" worktree add -q --detach "$AMD_CI_WORK/states/head" "$BASE_SHA"
          git -C "$AMD_CI_WORK/states/head" apply --index "$GITHUB_WORKSPACE/amd_ci/patches/rocm_flash.patch"
          git -C "$AMD_CI_WORK/states/head" diff --cached --stat
          python3 "$GITHUB_WORKSPACE/diffusion_bench/amd/write_states.py" --work "$AMD_CI_WORK" \\
            --base-sha "$BASE_SHA" --patch rocm_flash.patch --out "$AMD_CI_WORK/out/states.json"

      - name: Environment and real gate
        timeout-minutes: 60
        run: |
          set -euo pipefail
          cd "$AMD_CI_WORK/states/head"
          export UNSLOTH_STUDIO_HOME="$AMD_CI_WORK/studio"
          echo "UNSLOTH_STUDIO_HOME=$UNSLOTH_STUDIO_HOME" >> "$GITHUB_ENV"
          # The runners' uv index is a PyPI mirror that lags; give uv pypi.org as an extra index (scaffold default).
          export UV_EXTRA_INDEX_URL="https://pypi.org/simple"
          set +e
          bash install.sh --local 2>&1 | tail -15
          rc=${{PIPESTATUS[0]}}
          set -e
          [ "$rc" -eq 0 ] || exit "$rc"
          V=""
          for c in "$UNSLOTH_STUDIO_HOME"/unsloth_studio "$UNSLOTH_STUDIO_HOME"/.venv_t5_*; do
            [ -x "$c/bin/python" ] && {{ V="$c"; break; }}
          done
          [ -n "$V" ] || {{ echo "FATAL: no Studio venv"; exit 1; }}
          echo "AMD_CI_PY=$V/bin/python" >> "$GITHUB_ENV"
          "$V/bin/python" "$GITHUB_WORKSPACE/amd_ci/lib/gate.py" --require rocm gpu \\
            --expect-arch gfx1151 --min-gpus 1 --out "$AMD_CI_WORK/out/host.json"

      - name: flash-attention (DAO-AILab, Triton AMD backend) into the Studio venv
        timeout-minutes: 30
        run: |
          set +e
          git clone -q https://github.com/Dao-AILab/flash-attention "$AMD_CI_WORK/src/flash-attention"
          git -C "$AMD_CI_WORK/src/flash-attention" checkout -q "$FA_SHA"
          "$AMD_CI_PY" -m pip --version > /dev/null 2>&1 || "$AMD_CI_PY" -m ensurepip -q
          "$AMD_CI_PY" -c "import torch; print('studio torch before', torch.__version__)"
          "$AMD_CI_PY" -m pip install -q setuptools wheel packaging psutil ninja einops > "$AMD_CI_WORK/out/fa_studio_deps.log" 2>&1
          cd "$AMD_CI_WORK/src/flash-attention"
          FLASH_ATTENTION_TRITON_AMD_ENABLE=TRUE "$AMD_CI_PY" -m pip install --no-build-isolation --no-deps . > "$AMD_CI_WORK/out/fa_studio_build.log" 2>&1
          rc=$?
          echo "flash-attn into Studio venv: rc=$rc"
          tail -3 "$AMD_CI_WORK/out/fa_studio_build.log"
          "$AMD_CI_PY" -c "import torch; print('studio torch after', torch.__version__)"
          FLASH_ATTENTION_TRITON_AMD_ENABLE=TRUE "$AMD_CI_PY" "$GITHUB_WORKSPACE/diffusion_bench/amd/fa_smoke.py" \\
            --out "$AMD_CI_WORK/out/fa_smoke_studio.json"
          exit 0

      - name: ComfyUI (README ROCm install, own venv)
        timeout-minutes: 45
        run: |
          set +e
          git clone -q https://github.com/comfyanonymous/ComfyUI "$AMD_CI_WORK/ComfyUI"
          git -C "$AMD_CI_WORK/ComfyUI" checkout -q "$COMFY_SHA"
          BASEPY=$("$AMD_CI_PY" -c "import sys; print(sys._base_executable)")
          "$BASEPY" -m venv "$AMD_CI_WORK/comfy_venv_default"
          P="$AMD_CI_WORK/comfy_venv_default/bin/python"
          "$P" -m pip install -q --upgrade pip > /dev/null 2>&1
          # README, "AMD GPUs (Linux)": the stable ROCm wheel, then the requirements.
          "$P" -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm7.2 > "$AMD_CI_WORK/out/comfy_default_torch.log" 2>&1
          echo "README torch install rc=$?"
          "$P" -m pip install -r "$AMD_CI_WORK/ComfyUI/requirements.txt" > "$AMD_CI_WORK/out/comfy_default_reqs.log" 2>&1
          echo "requirements rc=$?"
          "$P" -c "import torch; print('comfy default torch', torch.__version__, 'hip', torch.version.hip, 'gpu', torch.cuda.is_available())"
          exit 0

      - name: ComfyUI venv on the gfx1151 torch Studio uses, + flash-attention
        timeout-minutes: 45
        run: |
          set +e
          TV=$("$AMD_CI_PY" -c "import torch; print(torch.__version__)")
          VV=$("$AMD_CI_PY" -c "import torchvision; print(torchvision.__version__)")
          BASEPY=$("$AMD_CI_PY" -c "import sys; print(sys._base_executable)")
          "$BASEPY" -m venv "$AMD_CI_WORK/comfy_venv_rock"
          P="$AMD_CI_WORK/comfy_venv_rock/bin/python"
          "$P" -m pip install -q --upgrade pip > /dev/null 2>&1
          "$P" -m pip install --index-url https://repo.amd.com/rocm/whl/gfx1151/ "torch==$TV" "torchvision==$VV" > "$AMD_CI_WORK/out/comfy_rock_torch.log" 2>&1
          echo "gfx1151 torch $TV install rc=$?"
          "$P" -m pip install -r "$AMD_CI_WORK/ComfyUI/requirements.txt" > "$AMD_CI_WORK/out/comfy_rock_reqs.log" 2>&1
          echo "requirements rc=$?"
          "$P" -m pip install -q setuptools wheel packaging psutil ninja einops > /dev/null 2>&1
          cd "$AMD_CI_WORK/src/flash-attention"
          FLASH_ATTENTION_TRITON_AMD_ENABLE=TRUE "$P" -m pip install --no-build-isolation --no-deps . > "$AMD_CI_WORK/out/fa_comfy_build.log" 2>&1
          echo "flash-attn into ComfyUI venv: rc=$?"
          "$P" -c "import torch; print('comfy rock torch', torch.__version__, 'expected $TV')"
          exit 0

      - name: Differential ({title})
        run: |
          set +e
          export TORCH_HOME="$AMD_CI_WORK/torch_home"
          export HF_HOME="$AMD_CI_WORK/hf_home"
          "$AMD_CI_PY" amd_ci/lib/differential.py \\
            --states "$AMD_CI_WORK/out/states.json" \\
            --probe diffusion_bench/amd/diffusion_probe.py \\
            --criteria diffusion_bench/amd/criteria_{criteria}.py \\
            --out-dir "$AMD_CI_WORK/out/gpu" \\
            --python "$AMD_CI_PY" -- {probe_args}
          cat "$AMD_CI_WORK/out/gpu/VERDICT.md" >> "$GITHUB_STEP_SUMMARY"
          python3 "$GITHUB_WORKSPACE/amd_ci/lib/announce.py" "$AMD_CI_WORK/out/gpu"

      - name: Stop anything this job started
        if: always()
        run: |
          set +e
          for d in /proc/[0-9]*; do
            pid=${{d#/proc/}}
            [ "$pid" = "$$" ] && continue
            cwd=$(readlink "$d/cwd" 2>/dev/null)
            case "$cwd" in
              "$AMD_CI_WORK"*) echo "stopping pid $pid (cwd $cwd)"; kill "$pid" 2>/dev/null ;;
            esac
          done
          exit 0

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: svc-{jid}
          path: |
            ${{{{ env.AMD_CI_WORK }}}}/out
            ${{{{ env.AMD_CI_WORK }}}}/dbench/states/*/runs/**/record.json
            ${{{{ env.AMD_CI_WORK }}}}/dbench/states/*/runs/**/*.png
            ${{{{ env.AMD_CI_WORK }}}}/dbench/states/*/runs/**/*.log
            ${{{{ env.AMD_CI_WORK }}}}/dbench/states/*/logs
          retention-days: 14
          if-no-files-found: warn
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required = True, type = Path)
    ap.add_argument("--budget-min", type = float, default = 420.0)
    ap.add_argument("--cell-timeout", type = float, default = 5400.0)
    args = ap.parse_args()
    text = HEADER
    prev = None
    for jid, title, only, head_only, criteria, defect in JOBS:
        pa = ["--spec", "diffusion_bench/specs/amd_studio_vs_comfy.json", "--budget-min", str(args.budget_min),
              "--cell-timeout", str(args.cell_timeout)]
        for o in only:
            pa += ["--only", o]
        for h in head_only:
            pa += ["--state-only", f"head={h}"]
        if defect:
            pa += ["--defect", defect]
        needs = f"    needs: [{prev}]\n    if: ${{{{ always() }}}}\n" if prev else ""
        text += JOB.format(jid = jid, title = title, needs = needs, criteria = criteria,
                           probe_args = " ".join(shlex.quote(a) for a in pa))
        prev = jid
    wf = args.out / ".github" / "workflows" / f"{BRANCH}.yml"
    wf.parent.mkdir(parents = True, exist_ok = True)
    for old in wf.parent.glob("*.yml"):
        if old != wf:
            old.unlink()
    wf.write_text(text, encoding = "utf-8")
    print(f"wrote {wf}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
