name: AMD DevLab Linux control

on:
  push:
    branches: [amd-devlab-lin-ci]

permissions: {}

jobs:
  linux:
    runs-on: [self-hosted, Linux, strix-halo, devlab-dispatch]
    timeout-minutes: 15
    steps:
      - name: Control
        run: |
          uname -a
          nproc
          free -h
